---
title: "Evaluation"
author: "朱立夫"
date: "2023-03-21"
output: 
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
---

# 基本统计运算
```{r}
library(skimr)
data <- read_excel("D:/课程/实训课数据/组别5/2016-12-10  校直幼儿园测量数据z.xlsx")
data <- read_excel("D:/课程/实训课数据/组别5/2014-12-25  校直幼儿园测量数据.xlsx")
skim(data)
data[177,8]= NA
data = data[,6:8]
colnames(data1) = c("a","h","w")
c=c()
for (i in 1:200) {
  imp = mice(data,m=4,meth = c("pmm"),seed =  i)
  c[i] = complete(imp)[238,3]}
table(c)
```


```{r}
data$年龄 = data$年龄 %>% round(1)
colnames(data)[7:8] = c("身高(cm)","体重(kg)")
data$`头围（cm）` = NA
data$h_Percecnt=(data[,7]-min(data[,7]))/(max(data[,7])-min(data[,7]))
data$h_Zscore =scale(data[,7],center=T,scale=T)
data$w_Percecnt=(data[,8]-min(data[,8]))/(max(data[,8])-min(data[,8]))
data$w_Zscore =scale(data[,8],center=T,scale=T)
# data[177,8] = data[177,11]*2.03+17.37
# data[177,8] = 17.5
# data[238,8] = data[238,11]*2.45+18.93
data$h_Percecnt=(data[,7]-min(data[,7]))/(max(data[,7])-min(data[,7]))
data$h_Zscore =scale(data[,7],center=T,scale=T)
data$w_Percecnt=(data[,8]-min(data[,8]))/(max(data[,8])-min(data[,8]))
data$w_Zscore =scale(data[,8],center=T,scale=T)
data$date = "2014"
data$BMI = data$`体重(kg)`/(data$`身高(cm)`/100)**2
data$BMI_Zscore = 0
for (i in 1:nrow(data)) {
  if (data[i,3] == "男") {
     if (data[i,6] %in% seq(2.5,3,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-95.4)/3.9
        data[i,13] = (data[i,8]-14.28)/1.64
        data[i,16] = (data[i,15]-15.67)/1.21}
     if (data[i,6] %in% seq(3.0,3.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-98.9)/3.8
        data[i,13] = (data[i,8]-15.31)/1.75
        data[i,16] = (data[i,15]-15.62)/1.21}
     if (data[i,6] %in% seq(3.5,4.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-102.4)/4
        data[i,13] = (data[i,8]-16.33)/1.97
        data[i,16] = (data[i,15]-15.53)/1.2}
     if (data[i,6] %in% seq(4.0,4.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-106.0)/4.1
        data[i,13] = (data[i,8]-17.37)/2.03
        data[i,16] = (data[i,15]-15.43)/1.22}
     if (data[i,6] %in% seq(4.5,5.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-109.5)/4.4
        data[i,13] = (data[i,8]-18.55)/2.27
        data[i,16] = (data[i,15]-15.43)/1.3}    
     if (data[i,6] %in% seq(5.0,5.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-113.1)/4.4
        data[i,13] = (data[i,8]-19.9)/2.61
        data[i,16] = (data[i,15]-15.52)/1.43}   
     if (data[i,6] %in% seq(5.5,6.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-116.4)/4.5
        data[i,13] = (data[i,8]-21.16)/2.82
        data[i,16] = (data[i,15]-15.58)/1.52} 
     if (data[i,6] %in% seq(6.0,6.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-120.0)/4.8
        data[i,13] = (data[i,8]-22.51)/3.21
        data[i,16] = (data[i,15]-15.58)/1.58} 
  }
  if (data[i,3] == "女") {
     if (data[i,6] %in% seq(3.0,3.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-97.6)/3.8
        data[i,13] = (data[i,8]-14.8)/1.69
        data[i,16] = (data[i,15]-15.5)/1.22}
     if (data[i,6] %in% seq(3.5,4.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-101.3)/3.8
        data[i,13] = (data[i,8]-14.8)/1.86
        data[i,16] = (data[i,15]-15.4)/1.22}
     if (data[i,6] %in% seq(4.0,4.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-104.9)/4.1
        data[i,13] = (data[i,8]-16.84)/2.02
        data[i,16] = (data[i,15]-15.27)/1.25}
     if (data[i,6] %in% seq(4.5,5.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-108.7)/4.3
        data[i,13] = (data[i,8]-18.01)/2.22
        data[i,16] = (data[i,15]-15.22)/1.31}    
     if (data[i,6] %in% seq(5.0,5.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-111.7)/4.4
        data[i,13] = (data[i,8]-18.93)/2.45
        data[i,16] = (data[i,15]-15.15)/1.42}   
     if (data[i,6] %in% seq(5.5,6.0,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-115.4)/4.5
        data[i,13] = (data[i,8]-20.27)/2.73
        data[i,16] = (data[i,15]-15.19)/1.45} 
     if (data[i,6] %in% seq(6.0,6.5,by = 0.1)
      ) {
        data[i,11] = (data[i,7]-118.9)/4.6
        data[i,13] = (data[i,8]-21.55)/2.94
        data[i,16] = (data[i,15]-15.19)/1.49} 
                }  
 
}

data$group = paste(data$date, data$性别, sep="_")
data$hz = "xia"
data$wz = "xia"
data$BMIz = "xia"
for (i in 1:nrow(data)) {
  if (data[i,11]<(-2)) {data[i,"hz"] = "下"}
  if (data[i,11]<(-1) & data[i,11]>(-2)) {data[i,"hz"]  ="中下"}
  if (data[i,11]<1 & data[i,11]>(-1)) {data[i,"hz"]  ="中"}
  if (data[i,11]<2 & data[i,11]>1) {data[i,"hz"]  ="中上"}
  if (data[i,11]>2) {data[i,"hz"]  ="上"}
  if (data[i,13]<(-2)) {data[i,"wz"]  ="下"}
  if (data[i,13]<(-1) & data[i,13]>(-2)) {data[i,"wz"]  ="中下"}
  if (data[i,13]<1 & data[i,13]>(-1)) {data[i,"wz"]  ="中"}
  if (data[i,13]<2 & data[i,13]>1) {data[i,"wz"]  ="中上"}
  if (data[i,13]>2) {data[i,"wz"]  ="上"}
  if (data[i,16]<(-2)) {data[i,"BMIz"]  ="下"}
  if (data[i,16]<(-1) & data[i,16]>(-2)) {data[i,"BMIz"]  ="中下"}
  if (data[i,16]<1 & data[i,16]>(-1)) {data[i,"BMIz"]  ="中"}
  if (data[i,16]<2 & data[i,16]>1) {data[i,"BMIz"]  ="中上"}
  if (data[i,16]>2) {data[i,"BMIz"]  ="上"}
}

table(data$年龄)
colnames(data)
data = rbind(data1,data2)
```


## 标准化

最大最小标准化
```{r}
b1=(data[,7]-min(data[,7]))/(max(data[,7])-min(data[,7]))

```
百分位数
```{r}
data$hperc <- ecdf(df$x)(df$x) * 100
```



零一标准化
x*=(x-均值)/标准差
```{r}
data_zscore=scale(data)

```

scale
```{r}
scale(x)=scale(x,center=T,scale=T)，#默认设置
scale(x,center=F,scale=T)#代表不进行中心化，直接做标准化；
scale(x,center=T,scale=F)#代表中心化
scale(x,center=F,scale=F)#代表什么不做，是原来的数据列。
```



##图表可视化
```{r, fig.height=4, fig.width=7,results="hide"}
library(ggplot2)
ggplot(data, aes(x=年龄, y=`体重(kg)`,color=性别,alpha = w_Zscore)) + 
  geom_point(size = 2.5,shape = 16)+
  facet_wrap(~性别)+
  theme_bw()+
  scale_colour_manual(values = c("green3", "orange1")) 

```

## pinshu
```{r, fig.height=2, fig.width=6.5,results="hide"}
ggplot(data[data[,3]=="女",], aes(`身高(cm)`)) + theme_bw()+
  geom_histogram(aes(y = ..density..),
                 binwidth = 1,col = "orange1",fill = "orange1",alpha =0.4)+
   geom_density(aes(y = ..density..),colour = "orange1",fill = "orange1",alpha =0.2)+
  scale_x_continuous(limits =c(90,127),
         breaks = seq(90, 127, 2))

ggplot(data[data[,3]=="男",], aes(`身高(cm)`)) + theme_bw()+
  geom_histogram(aes(y = ..density..),
                 binwidth = 1,col = "green3",fill = "green3",alpha =0.4)+
   geom_density(aes(y = ..density..),colour = "green3",fill = "green3",alpha =0.2)+
  scale_x_continuous(limits =c(90,130),
         breaks = seq(90, 130, 2))

```

```{r, fig.height=2, fig.width=6,results="hide"}
ggplot(data[data[,3]=="女",], aes(`体重(kg)`)) + theme_bw()+
  geom_histogram(aes(y = ..density..),
                 binwidth = 1,col = "orange1",fill = "orange1",alpha =0.4)+
   geom_density(aes(y = ..density..),colour = "orange1",fill = "orange1",alpha =0.2)+
  scale_x_continuous(limits = c(11,31),
         breaks = seq(11, 31, 1))


ggplot(data[data[,3]=="男",], aes(`体重(kg)`)) + theme_bw()+
  geom_histogram(aes(y = ..density..),
                 binwidth = 1,col = "green3",fill = "green3",alpha =0.4)+
   geom_density(aes(y = ..density..),colour = "green3",fill = "green3",alpha =0.2)+
  scale_x_continuous(limits = c(11,30),
         breaks = seq(11, 30, 1))
```

```{r, fig.height=2, fig.width=6.5,results="hide"}
ggplot(data[data[,3]=="女",], aes(BMI)) + theme_bw()+
  geom_histogram(aes(y = ..count..),
                 binwidth = 1,col = "orange1",fill = "orange1",alpha =0.4)+
   geom_density(aes(y = ..count..),colour = "orange1",fill = "orange1",alpha =0.2)+
  scale_x_continuous(limits =c(12,22),
         breaks = seq(12, 22, 1))

ggplot(data[data[,3]=="男",], aes(BMI)) + theme_bw()+
  geom_histogram(aes(y = ..count..),
                 binwidth = 1,col = "green3",fill = "green3",alpha =0.4)+
   geom_density(aes(y = ..count..),colour = "green3",fill = "green3",alpha =0.2)+
  scale_x_continuous(limits =c(12,22),
         breaks = seq(12, 22, 1))

```


## Zscore
```{r}
ggplot(data[data[,3]=="女",], aes(h_Zscore)) + theme_bw()+
  geom_histogram(binwidth = 0.5,fill = "orange1",alpha =0.5,col = "orange1",show.legend=T)+
  scale_x_continuous(limits = c(-3.5,3.5),
         breaks = seq(-3.5, 3.5, 0.5))
c(
nrow(data[data[,3]=="女" & data[,16]< (-2),]),
nrow(data[data[,3]=="女" & data[,16]> (-2) & data[,16]< (-1),]),
nrow(data[data[,3]=="女" & data[,16]> (-1) & data[,16]<1,]),
nrow(data[data[,3]=="女" & data[,16]>1 & data[,16]<2,]),
nrow(data[data[,3]=="女" & data[,16]>2,]))

```

```{r}
ggplot(data[data[,3]=="男",], aes(h_Zscore)) + theme_bw()+
  geom_histogram(binwidth = 0.5,fill = "green3",alpha =0.5,col = "green3",show.legend=T)+
  scale_x_continuous(limits = c(-3.5,3.5),
         breaks = seq(-3.5, 3.5, 0.5))
c(
nrow(data[data[,3]=="男" & data[,16]< (-2),]),
nrow(data[data[,3]=="男" & data[,16]> (-2) & data[,16]< (-1),]),
nrow(data[data[,3]=="男" & data[,16]> (-1) & data[,16]<1,]),
nrow(data[data[,3]=="男" & data[,16]>1 & data[,16]<2,]),
nrow(data[data[,3]=="男" & data[,16]>2,]))

```


https://cloud.tencent.com/developer/article/1966671
https://www.jianshu.com/p/fa8f062ff467
```{r}
library(ggstatsplot)
ggbetweenstats(data,x = 性别,y =`身高(cm)`,
               bf.message = T,     ##关闭贝叶斯检验的信息
               outlier.tagging = TRUE, ## 选择显示离群值
               plot.type = "boxviolin", # box, boxviolin, violin
               type = "p") +# p"  → parametric  np" → non-parametric
                           # "r"  → robust  "bf" → Bayesian  可选统计类型包括
             scale_colour_manual(values = c("green3", "orange1"))
```


```{r}
ggbetweenstats(
  data = data1,
  x = gender,    ##分组变量
  y = math1,     ##响应变量
  type = "p",    ##选择参数检验
  effsize.type = "g",     ##选择无偏估计的T检验
  conf.level = 0.95,      ##95%的置信区间
  k = 3L,                 ##保留3位小数
  bf.message = FALSE,     ##关闭贝叶斯检验的信息
  outlier.tagging = TRUE, ## 选择显示离群值
  outlier.label = name,   ##离群值标签
  outlier.label.args = list(color = "green3", size = 2), ##将离群值的颜色设置为蓝色，大小为2
  xlab = "Gender",        ##横坐标标签
  ylab = "Math Scores",   ##纵坐标标签
  plot.type = "boxviolin",##将图形设置为小提琴和箱型图混合
  palette = "Set2",       ##调色板
  ggtheme = ggplot2::theme_gray(),  ##设置主题
  title = "Comparison of male and female students' first math scores",   ##标题
  caption = "Source: Rui Wang"  ##说明文字
) +
  ggplot2::scale_y_continuous(  ##设置纵轴
    limits = c(20,100),
    breaks = seq(from = 20, to = 100, by = 20)
  )+
  theme(plot.title = element_text(hjust = 0.5,size = 14),  ##设置字体大小
        plot.caption = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10))
```

```{r}
ggbetweenstats(data,x = 性别,y = `体重(kg)`,
               
               plot.type = "boxviolin", # box, boxviolin, violin
               type = "p") +# p"  → parametric  np" → non-parametric
                           # "r"  → robust  "bf" → Bayesian  可选统计类型包括
  # 参数(parametric|p)、非参数(nonparametric|np)、稳健(robust|r)、贝叶斯(bayes|bf)
pairwise.comparisons = TRUE,           ##是否进行成对比较
             scale_colour_manual(values = c("green3", "orange1")) 
```

```{r}
ggbetweenstats(data,x = 性别,y = BMI,
               
               plot.type = "boxviolin", # box, boxviolin, violin
               type = "p") +# p"  → parametric  np" → non-parametric
                           # "r"  → robust  "bf" → Bayesian  可选统计类型包括
             scale_colour_manual(values = c("green3", "orange1")) 
```

```{r}
ggwithinstats(
  data = data[data[,3]=="女",],
  x = date,
  y = BMI,
  caption = ,
  type = "r", ## 统计方法
  bf.message = TRUE,
  results.subtitle = TRUE,
  # xlab = "Condition", ## x轴的label
  # ylab = "Desire to kill an artrhopod", ## y轴的label
  effsize.type = "biased", ## 效应值类型
  sphericity.correction = T, ## 不显示校正后的DFS和P值
  pairwise.comparisons = F, ## 显示配对比较
  outlier.tagging = TRUE, ## 是否标记outlier
  outlier.coef = 1.5, ##  Tukey's rule的系数
  # outlier.label = region, ## 标记outlier的label
  outlier.label.color = "red", ## 标记outlier的label的颜色
  mean.plotting = TRUE, ## 是否显示均值
  point.path = T,# 连线
  mean.color = "darkblue", ## 均值的颜色
  package = "yarrr", ## 颜色所取的包
  palette = "info2", ## 所取的调色板
  # title = "Comparison of desire to kill bugs",
  # caption = "Source: Ryan et al., 2013"
)+scale_colour_manual(values = c("red", "#FFA500")) # "blue", "seagreen2"     "red", "#FFA500"
```

https://zhuanlan.zhihu.com/p/580374939
```{r}
ggwithinstats(
  data = data,
  x = group,
  y = `体重(kg)`,
  type = "r")+
  scale_colour_manual(values = c("blue","red","green3", "orange1"))

```


```{r}
gghistostats(data = data, x = `体重(kg)`, test.value = 6)
```

## 占比
https://mp.weixin.qq.com/s?__biz=MzkxOTM5MzQwNQ==&mid=2247484294&idx=1&sn=6f5ce38c1b3c6b61ef6c60df3aca0717&chksm=c1a38694f6d40f8202558d83d8332598d36325dfe28332113446394bac7ffce3256f982d310b&cur_album_id=2502497412276797443&scene=189#wechat_redirect
```{r}
library(ggplot2)
cellnum <- table(data$BMIz,data$group)
cell.prop<-as.data.frame(prop.table(cellnum))# 函数求细胞比例
colnames(cell.prop)<-c("grade","group","Proportion")
      cell.prop$grade<-factor(cell.prop$grade,levels =  c("上","中上","中","中下","下")) 
      cell.prop$group<-factor(cell.prop$group,levels =  c("2014_男","2016_男","2014_女","2016_女")) 
      cell.prop = cell.prop[order(cell.prop$grade,cell.prop$group),]
p.bar <- ggplot(cell.prop,aes(group,Proportion,fill=grade))+
  geom_bar(stat="identity",position="fill")+
  #scale_fill_manual(values=cols)+#自定义fill的颜色
  ggtitle("BMI Z grade proportion")+
  theme_bw()+
  theme(axis.ticks.length=unit(0.5,'cm'))+
  guides(fill=guide_legend(title=NULL))+
    scale_fill_d3()
p.bar
```

```{r}
data$BMIz<-factor(data$BMIz,levels =  rev(c("上","中上","中","中下","下"))) 
data$group<-factor(data$group,levels =  c("2014_男","2016_男","2014_女","2016_女")) 
ggbarstats(data,
           x = hz, 
           y = group,
           label = "both", #
           type = "r",
           label.text.size = 5, #字体大小
           label.args = list(alpha = 0.8, fill = "white"),
           package = "ggsci",
           palette = "category20_d3",
  label.repel = T,
   bf.message = T)+
  theme(plot.title = element_text(hjust = 0.5,size = 50),  ##设置字体大小
        plot.caption = element_text(size = 12),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10))
           
```

```{r}
ggpiestats(
  data = data,
  x = BMIz,
  y = group,
  label.repel = T,
   bf.message = F,
  label.text.size = 0.5, #字体大小
  label.args = list(alpha = 0.8, fill = "white"),
           package = "ggsci",
           palette = "category20_d3",
  legend.title = ""
) + # further modification with `{ggplot2}` commands
  ggplot2::theme(
    plot.title = ggplot2::element_text(
      color = "black",
      size = 0.5,
      hjust = 0
    )
  )
```

